name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t chidojiro/web-template:$(jq -r .version package.json) .

      - name: Push the Docker image to Docker Hub
        run: docker push chidojiro/web-template:$(jq -r .version package.json)
